### PR TITLE
feat: Change token syntax to api keys (setup branch

### PR DESCRIPTION
**Pull request by dcorso21**

### CODE REVIEW

**Comment by borislobanov92** [comment]
@dcorso21 this PR is against the wrong branch, it should be against main/master. This branch is here for anyone who wants to follow the steps from the tutorial from scratch. Also we might need to add some captions to the video now that we've changed the API but I'm not sure that it's worth spending time.

**Comment by dcorso21** [comment]
@borislobanov1703, I actually created 3 pull requests - one for each branch to change the syntax. 

> Also we might need to add some captions to the video now that we've changed the API but I'm not sure that it's worth spending time.

Personally I'm not sure it's not worth the effort.

**Comment by borislobanov92** [comment]
@dcorso21 but this one adds all the changes from the master branch to the initial set up branch, we need to keep this branch intact for those who want to follow along with the tutorial

**Comment by dcorso21** [comment]
@borislobanov1703 , my mistake. I'm closing this PR now.

**Pull request closed without merging**
